[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm cache clean --force",
  "npm install --no-optional"
]

[phases.build]
cmds = []

[start]
cmd = "node src/index.js"